//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.TestAntigonisInformationClient.InformationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationMessageBase", Namespace="http://schemas.datacontract.org/2004/07/AntigonisTypes.Information")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageRequest))]
    public partial class InformationMessageBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullMessageTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullMessageText {
            get {
                return this.FullMessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.FullMessageTextField, value) != true)) {
                    this.FullMessageTextField = value;
                    this.RaisePropertyChanged("FullMessageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageBody {
            get {
                return this.MessageBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageBodyField, value) != true)) {
                    this.MessageBodyField = value;
                    this.RaisePropertyChanged("MessageBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTypeField, value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationMessageResponse", Namespace="http://schemas.datacontract.org/2004/07/AntigonisTypes.Information")]
    [System.SerializableAttribute()]
    public partial class InformationMessageResponse : Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Corp.TestAntigonisInformationClient.InformationServiceReference.HsmError ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Corp.TestAntigonisInformationClient.InformationServiceReference.HsmError ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationMessageRequest", Namespace="http://schemas.datacontract.org/2004/07/AntigonisTypes.Information")]
    [System.SerializableAttribute()]
    public partial class InformationMessageRequest : Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HsmError", Namespace="http://schemas.datacontract.org/2004/07/AntigonisTypes")]
    public enum HsmError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoError = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CvvVerificationFailed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CvkParityError = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidInputData = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CvkNotDoubleLength = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommandDisabled = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralError = -2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationServerFault", Namespace="http://schemas.datacontract.org/2004/07/AntigonisTypes")]
    [System.SerializableAttribute()]
    public partial class InformationServerFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InformationServiceReference.IInformationServer")]
    public interface IInformationServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformationServer/ProcessInformationRequest", ReplyAction="http://tempuri.org/IInformationServer/ProcessInformationRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Corp.TestAntigonisInformationClient.InformationServiceReference.InformationServerFault), Action="http://tempuri.org/IInformationServer/ProcessInformationRequestInformationServerF" +
            "aultFault", Name="InformationServerFault", Namespace="http://schemas.datacontract.org/2004/07/AntigonisTypes")]
        Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageResponse ProcessInformationRequest(Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformationServer/Ping", ReplyAction="http://tempuri.org/IInformationServer/PingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Corp.TestAntigonisInformationClient.InformationServiceReference.InformationServerFault), Action="http://tempuri.org/IInformationServer/PingInformationServerFaultFault", Name="InformationServerFault", Namespace="http://schemas.datacontract.org/2004/07/AntigonisTypes")]
        Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageResponse Ping(Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInformationServerChannel : Corp.TestAntigonisInformationClient.InformationServiceReference.IInformationServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformationServerClient : System.ServiceModel.ClientBase<Corp.TestAntigonisInformationClient.InformationServiceReference.IInformationServer>, Corp.TestAntigonisInformationClient.InformationServiceReference.IInformationServer {
        
        public InformationServerClient() {
        }
        
        public InformationServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InformationServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageResponse ProcessInformationRequest(Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageRequest request) {
            return base.Channel.ProcessInformationRequest(request);
        }
        
        public Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageResponse Ping(Corp.TestAntigonisInformationClient.InformationServiceReference.InformationMessageRequest request) {
            return base.Channel.Ping(request);
        }
    }
}
