//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.HSMServiceProxy.HsmServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HsmServiceReference.IHsm")]
    public interface IHsm {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsm/HsmRequest", ReplyAction="http://tempuri.org/IHsm/HsmRequestResponse")]
        AntigonisTypes.HsmMessageResponse HsmRequest([System.ServiceModel.MessageParameterAttribute(Name="hsmRequest")] AntigonisTypes.HsmMessageRequest hsmRequest1);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHsm/HsmRequest", ReplyAction="http://tempuri.org/IHsm/HsmRequestResponse")]
        System.IAsyncResult BeginHsmRequest(AntigonisTypes.HsmMessageRequest hsmRequest, System.AsyncCallback callback, object asyncState);
        
        AntigonisTypes.HsmMessageResponse EndHsmRequest(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHsmChannel : Corp.HSMServiceProxy.HsmServiceReference.IHsm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HsmRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HsmRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AntigonisTypes.HsmMessageResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AntigonisTypes.HsmMessageResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HsmClient : System.ServiceModel.ClientBase<Corp.HSMServiceProxy.HsmServiceReference.IHsm>, Corp.HSMServiceProxy.HsmServiceReference.IHsm {
        
        private BeginOperationDelegate onBeginHsmRequestDelegate;
        
        private EndOperationDelegate onEndHsmRequestDelegate;
        
        private System.Threading.SendOrPostCallback onHsmRequestCompletedDelegate;
        
        public HsmClient() {
        }
        
        public HsmClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HsmClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HsmClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HsmClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<HsmRequestCompletedEventArgs> HsmRequestCompleted;
        
        public AntigonisTypes.HsmMessageResponse HsmRequest(AntigonisTypes.HsmMessageRequest hsmRequest1) {
            return base.Channel.HsmRequest(hsmRequest1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHsmRequest(AntigonisTypes.HsmMessageRequest hsmRequest, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHsmRequest(hsmRequest, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AntigonisTypes.HsmMessageResponse EndHsmRequest(System.IAsyncResult result) {
            return base.Channel.EndHsmRequest(result);
        }
        
        private System.IAsyncResult OnBeginHsmRequest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AntigonisTypes.HsmMessageRequest hsmRequest = ((AntigonisTypes.HsmMessageRequest)(inValues[0]));
            return this.BeginHsmRequest(hsmRequest, callback, asyncState);
        }
        
        private object[] OnEndHsmRequest(System.IAsyncResult result) {
            AntigonisTypes.HsmMessageResponse retVal = this.EndHsmRequest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHsmRequestCompleted(object state) {
            if ((this.HsmRequestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HsmRequestCompleted(this, new HsmRequestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HsmRequestAsync(AntigonisTypes.HsmMessageRequest hsmRequest) {
            this.HsmRequestAsync(hsmRequest, null);
        }
        
        public void HsmRequestAsync(AntigonisTypes.HsmMessageRequest hsmRequest, object userState) {
            if ((this.onBeginHsmRequestDelegate == null)) {
                this.onBeginHsmRequestDelegate = new BeginOperationDelegate(this.OnBeginHsmRequest);
            }
            if ((this.onEndHsmRequestDelegate == null)) {
                this.onEndHsmRequestDelegate = new EndOperationDelegate(this.OnEndHsmRequest);
            }
            if ((this.onHsmRequestCompletedDelegate == null)) {
                this.onHsmRequestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHsmRequestCompleted);
            }
            base.InvokeAsync(this.onBeginHsmRequestDelegate, new object[] {
                        hsmRequest}, this.onEndHsmRequestDelegate, this.onHsmRequestCompletedDelegate, userState);
        }
    }
}
