//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.OperationServiceProxy.OperationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationMessageBase", Namespace="http://schemas.datacontract.org/2004/07/AntigonisTypes.Operation")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Corp.OperationServiceProxy.OperationServiceReference.OperationCardSummaryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Corp.OperationServiceProxy.OperationServiceReference.OperationPingRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Corp.OperationServiceProxy.OperationServiceReference.OperationPingResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Corp.OperationServiceProxy.OperationServiceReference.OperationGetCardSumRequest))]
    public partial class OperationMessageBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullMessageTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullMessageText {
            get {
                return this.FullMessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.FullMessageTextField, value) != true)) {
                    this.FullMessageTextField = value;
                    this.RaisePropertyChanged("FullMessageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageBody {
            get {
                return this.MessageBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageBodyField, value) != true)) {
                    this.MessageBodyField = value;
                    this.RaisePropertyChanged("MessageBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTypeField, value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationCardSummaryResponse", Namespace="http://schemas.datacontract.org/2004/07/Corp.RouterService.Adapter.WcfAdapter")]
    [System.SerializableAttribute()]
    public partial class OperationCardSummaryResponse : Corp.OperationServiceProxy.OperationServiceReference.OperationMessageBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationPingRequest", Namespace="http://schemas.datacontract.org/2004/07/Corp.RouterService.Adapter.WcfAdapter")]
    [System.SerializableAttribute()]
    public partial class OperationPingRequest : Corp.OperationServiceProxy.OperationServiceReference.OperationMessageBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationPingResponse", Namespace="http://schemas.datacontract.org/2004/07/Corp.RouterService.Adapter.WcfAdapter")]
    [System.SerializableAttribute()]
    public partial class OperationPingResponse : Corp.OperationServiceProxy.OperationServiceReference.OperationMessageBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationGetCardSumRequest", Namespace="http://schemas.datacontract.org/2004/07/Corp.RouterService.Adapter.WcfAdapter")]
    [System.SerializableAttribute()]
    public partial class OperationGetCardSumRequest : Corp.OperationServiceProxy.OperationServiceReference.OperationMessageBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperationServiceReference.IOperationService")]
    public interface IOperationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationService/GetCardSum", ReplyAction="http://tempuri.org/IOperationService/GetCardSumResponse")]
        Corp.OperationServiceProxy.OperationServiceReference.OperationCardSummaryResponse GetCardSum(Corp.OperationServiceProxy.OperationServiceReference.OperationGetCardSumRequest getCardSumRequest);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOperationService/GetCardSum", ReplyAction="http://tempuri.org/IOperationService/GetCardSumResponse")]
        System.IAsyncResult BeginGetCardSum(Corp.OperationServiceProxy.OperationServiceReference.OperationGetCardSumRequest getCardSumRequest, System.AsyncCallback callback, object asyncState);
        
        Corp.OperationServiceProxy.OperationServiceReference.OperationCardSummaryResponse EndGetCardSum(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationService/Ping", ReplyAction="http://tempuri.org/IOperationService/PingResponse")]
        Corp.OperationServiceProxy.OperationServiceReference.OperationPingResponse Ping(Corp.OperationServiceProxy.OperationServiceReference.OperationPingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOperationService/Ping", ReplyAction="http://tempuri.org/IOperationService/PingResponse")]
        System.IAsyncResult BeginPing(Corp.OperationServiceProxy.OperationServiceReference.OperationPingRequest request, System.AsyncCallback callback, object asyncState);
        
        Corp.OperationServiceProxy.OperationServiceReference.OperationPingResponse EndPing(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperationServiceChannel : Corp.OperationServiceProxy.OperationServiceReference.IOperationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCardSumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCardSumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Corp.OperationServiceProxy.OperationServiceReference.OperationCardSummaryResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Corp.OperationServiceProxy.OperationServiceReference.OperationCardSummaryResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Corp.OperationServiceProxy.OperationServiceReference.OperationPingResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Corp.OperationServiceProxy.OperationServiceReference.OperationPingResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationServiceClient : System.ServiceModel.ClientBase<Corp.OperationServiceProxy.OperationServiceReference.IOperationService>, Corp.OperationServiceProxy.OperationServiceReference.IOperationService {
        
        private BeginOperationDelegate onBeginGetCardSumDelegate;
        
        private EndOperationDelegate onEndGetCardSumDelegate;
        
        private System.Threading.SendOrPostCallback onGetCardSumCompletedDelegate;
        
        private BeginOperationDelegate onBeginPingDelegate;
        
        private EndOperationDelegate onEndPingDelegate;
        
        private System.Threading.SendOrPostCallback onPingCompletedDelegate;
        
        public OperationServiceClient() {
        }
        
        public OperationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetCardSumCompletedEventArgs> GetCardSumCompleted;
        
        public event System.EventHandler<PingCompletedEventArgs> PingCompleted;
        
        public Corp.OperationServiceProxy.OperationServiceReference.OperationCardSummaryResponse GetCardSum(Corp.OperationServiceProxy.OperationServiceReference.OperationGetCardSumRequest getCardSumRequest) {
            return base.Channel.GetCardSum(getCardSumRequest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCardSum(Corp.OperationServiceProxy.OperationServiceReference.OperationGetCardSumRequest getCardSumRequest, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCardSum(getCardSumRequest, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Corp.OperationServiceProxy.OperationServiceReference.OperationCardSummaryResponse EndGetCardSum(System.IAsyncResult result) {
            return base.Channel.EndGetCardSum(result);
        }
        
        private System.IAsyncResult OnBeginGetCardSum(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Corp.OperationServiceProxy.OperationServiceReference.OperationGetCardSumRequest getCardSumRequest = ((Corp.OperationServiceProxy.OperationServiceReference.OperationGetCardSumRequest)(inValues[0]));
            return this.BeginGetCardSum(getCardSumRequest, callback, asyncState);
        }
        
        private object[] OnEndGetCardSum(System.IAsyncResult result) {
            Corp.OperationServiceProxy.OperationServiceReference.OperationCardSummaryResponse retVal = this.EndGetCardSum(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCardSumCompleted(object state) {
            if ((this.GetCardSumCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCardSumCompleted(this, new GetCardSumCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCardSumAsync(Corp.OperationServiceProxy.OperationServiceReference.OperationGetCardSumRequest getCardSumRequest) {
            this.GetCardSumAsync(getCardSumRequest, null);
        }
        
        public void GetCardSumAsync(Corp.OperationServiceProxy.OperationServiceReference.OperationGetCardSumRequest getCardSumRequest, object userState) {
            if ((this.onBeginGetCardSumDelegate == null)) {
                this.onBeginGetCardSumDelegate = new BeginOperationDelegate(this.OnBeginGetCardSum);
            }
            if ((this.onEndGetCardSumDelegate == null)) {
                this.onEndGetCardSumDelegate = new EndOperationDelegate(this.OnEndGetCardSum);
            }
            if ((this.onGetCardSumCompletedDelegate == null)) {
                this.onGetCardSumCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCardSumCompleted);
            }
            base.InvokeAsync(this.onBeginGetCardSumDelegate, new object[] {
                        getCardSumRequest}, this.onEndGetCardSumDelegate, this.onGetCardSumCompletedDelegate, userState);
        }
        
        public Corp.OperationServiceProxy.OperationServiceReference.OperationPingResponse Ping(Corp.OperationServiceProxy.OperationServiceReference.OperationPingRequest request) {
            return base.Channel.Ping(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPing(Corp.OperationServiceProxy.OperationServiceReference.OperationPingRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPing(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Corp.OperationServiceProxy.OperationServiceReference.OperationPingResponse EndPing(System.IAsyncResult result) {
            return base.Channel.EndPing(result);
        }
        
        private System.IAsyncResult OnBeginPing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Corp.OperationServiceProxy.OperationServiceReference.OperationPingRequest request = ((Corp.OperationServiceProxy.OperationServiceReference.OperationPingRequest)(inValues[0]));
            return this.BeginPing(request, callback, asyncState);
        }
        
        private object[] OnEndPing(System.IAsyncResult result) {
            Corp.OperationServiceProxy.OperationServiceReference.OperationPingResponse retVal = this.EndPing(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPingCompleted(object state) {
            if ((this.PingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PingCompleted(this, new PingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PingAsync(Corp.OperationServiceProxy.OperationServiceReference.OperationPingRequest request) {
            this.PingAsync(request, null);
        }
        
        public void PingAsync(Corp.OperationServiceProxy.OperationServiceReference.OperationPingRequest request, object userState) {
            if ((this.onBeginPingDelegate == null)) {
                this.onBeginPingDelegate = new BeginOperationDelegate(this.OnBeginPing);
            }
            if ((this.onEndPingDelegate == null)) {
                this.onEndPingDelegate = new EndOperationDelegate(this.OnEndPing);
            }
            if ((this.onPingCompletedDelegate == null)) {
                this.onPingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPingCompleted);
            }
            base.InvokeAsync(this.onBeginPingDelegate, new object[] {
                        request}, this.onEndPingDelegate, this.onPingCompletedDelegate, userState);
        }
    }
}
