//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.TestRouterServiceWcfServer.RouterServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RouterServiceProxy.IThreePleLayerSecurityServer")]
    public interface IThreePleLayerSecurityServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThreePleLayerSecurityServer/ProcessThreePleLayerSecurityRequest", ReplyAction="http://tempuri.org/IThreePleLayerSecurityServer/ProcessThreePleLayerSecurityRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AntigonisTypes.ThreePleLayerSecurityServerFault), Action="http://tempuri.org/IThreePleLayerSecurityServer/ProcessThreePleLayerSecurityRequestThreePleLayerSecurityServ" +
            "erFaultFault", Name="ThreePleLayerSecurityServerFault", Namespace="http://schemas.datacontract.org/2004/07/AntigonisTypes")]
        AntigonisTypes.ThreePleLayerSecurity.ThreePleLayerSecurityMessageResponse ProcessThreePleLayerSecurityRequest(AntigonisTypes.ThreePleLayerSecurity.ThreePleLayerSecurityMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThreePleLayerSecurityServer/Ping", ReplyAction="http://tempuri.org/IThreePleLayerSecurityServer/PingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AntigonisTypes.ThreePleLayerSecurityServerFault), Action="http://tempuri.org/IThreePleLayerSecurityServer/PingThreePleLayerSecurityServerFaultFault", Name="ThreePleLayerSecurityServerFault", Namespace="http://schemas.datacontract.org/2004/07/AntigonisTypes")]
        AntigonisTypes.ThreePleLayerSecurity.ThreePleLayerSecurityMessageResponse Ping(AntigonisTypes.ThreePleLayerSecurity.ThreePleLayerSecurityMessageRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IThreePleLayerSecurityServerChannel : Corp.TestRouterServiceWcfServer.RouterServiceProxy.IThreePleLayerSecurityServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThreePleLayerSecurityServerClient : System.ServiceModel.ClientBase<Corp.TestRouterServiceWcfServer.RouterServiceProxy.IThreePleLayerSecurityServer>, Corp.TestRouterServiceWcfServer.RouterServiceProxy.IThreePleLayerSecurityServer {
        
        public ThreePleLayerSecurityServerClient() {
        }
        
        public ThreePleLayerSecurityServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThreePleLayerSecurityServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThreePleLayerSecurityServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThreePleLayerSecurityServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AntigonisTypes.ThreePleLayerSecurity.ThreePleLayerSecurityMessageResponse ProcessThreePleLayerSecurityRequest(AntigonisTypes.ThreePleLayerSecurity.ThreePleLayerSecurityMessageRequest request) {
            return base.Channel.ProcessThreePleLayerSecurityRequest(request);
        }
        
        public AntigonisTypes.ThreePleLayerSecurity.ThreePleLayerSecurityMessageResponse Ping(AntigonisTypes.ThreePleLayerSecurity.ThreePleLayerSecurityMessageRequest request) {
            return base.Channel.Ping(request);
        }
    }
}
